---- Base app schema


-- User
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,
  typ user_typ NOT NULL DEFAULT 'User',

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE "user" ADD CONSTRAINT fk_user_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE "user" ADD CONSTRAINT fk_user_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;

-- Org
CREATE TYPE org_kind AS ENUM ('Personal', 'Corporate');

CREATE TABLE org (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties
  name varchar(256),
  kind org_kind NOT NULL default 'Personal',

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE org ADD CONSTRAINT fk_org_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE org ADD CONSTRAINT fk_org_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;



-- Org Participants
CREATE TABLE user_org (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties / FKs
  org_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL, 

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL    
);

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_org_id
  FOREIGN KEY (org_id) REFERENCES "org"(id)
  ON DELETE CASCADE;

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_user_id
  FOREIGN KEY (user_id) REFERENCES "user"(id)
  ON DELETE CASCADE;

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;