---- Base app schema

-- user access modifiers, with their negatives
CREATE TYPE user_access AS ENUM (
  'a_ui',
  'a_api',
  'a_admin'
);


-- User
CREATE TYPE user_typ AS ENUM ('Sys', 'User');

CREATE TABLE "user" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL UNIQUE,
  typ user_typ NOT NULL DEFAULT 'User',
  uuid uuid NOT NULL,

  -- access modifiers
  accesses user_access[],

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid(),

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE "user" ADD CONSTRAINT fk_user_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE "user" ADD CONSTRAINT fk_user_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;

-- Org
CREATE TYPE org_kind AS ENUM ('Personal', 'Corporate');

CREATE TABLE org (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties
  name varchar(256),
  kind org_kind NOT NULL default 'Personal',
  uuid uuid NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL  
);

ALTER TABLE org ADD CONSTRAINT fk_org_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE org ADD CONSTRAINT fk_org_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;


CREATE TYPE orole_name AS ENUM (
  'or_owner',
  'or_admin',
  'or_editor',
  'or_viewer'
);

-- Org Participants
CREATE TABLE user_org (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties / FKs
  org_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL, 
  "role" orole_name NOT NULL,

  -- Timestamps
  cid bigint NOT NULL,
  ctime timestamp with time zone NOT NULL,
  mid bigint NOT NULL,
  mtime timestamp with time zone NOT NULL    
);

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_org_id
  FOREIGN KEY (org_id) REFERENCES "org"(id)
  ON DELETE CASCADE;

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_user_id
  FOREIGN KEY (user_id) REFERENCES "user"(id)
  ON DELETE CASCADE;

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE user_org ADD CONSTRAINT fk_user_org_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;

-- Pack
CREATE TABLE pack (
  -- PK
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  -- Properties
  org_id BIGINT NOT NULL,
  name VARCHAR(256) NOT NULL,

  -- Timestamps
  cid BIGINT NOT NULL,
  ctime TIMESTAMP WITH TIME ZONE NOT NULL,
  mid BIGINT NOT NULL,
  mtime TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE pack ADD CONSTRAINT fk_pack_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE pack ADD CONSTRAINT fk_pack_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE pack ADD CONSTRAINT fk_pack_org_id
  FOREIGN KEY (org_id) REFERENCES "org"(id)
  ON DELETE SET NULL;


-- Pack Versions
CREATE TABLE pack_version (
    id BIGSERIAL PRIMARY KEY,
    org_id BIGINT NOT NULL,
    pack_id BIGINT NOT NULL,
    version VARCHAR(50) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size BIGINT NOT NULL,
    changelog TEXT,
    cid BIGINT NOT NULL,
    ctime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    mid BIGINT NOT NULL,
    mtime TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX pack_version_unique_idx ON pack_version (pack_id, version);

ALTER TABLE pack_version ADD CONSTRAINT fk_pack_version_pack_id
  FOREIGN KEY (pack_id) REFERENCES "pack"(id)
  ON DELETE CASCADE;

ALTER TABLE pack_version ADD CONSTRAINT fk_pack_version_cid
  FOREIGN KEY (cid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE pack_version ADD CONSTRAINT fk_pack_version_mid
  FOREIGN KEY (mid) REFERENCES "user"(id)
  ON DELETE SET NULL;

ALTER TABLE pack_version ADD CONSTRAINT fk_pack_version_org_id
  FOREIGN KEY (org_id) REFERENCES "org"(id)
  ON DELETE SET NULL;

  
CREATE TABLE "prlink" (
  id bigserial PRIMARY KEY,

  "user_id" bigint not null,
  code uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),

  cid bigint,
  ctime TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  mid bigint,
  mtime TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE prlink ADD CONSTRAINT fk_prlink_user_id FOREIGN KEY ("user_id") REFERENCES "user" (id) ON DELETE CASCADE;
ALTER TABLE prlink ADD CONSTRAINT fk_prlink_mid FOREIGN KEY ("mid") REFERENCES "user" (id) ON DELETE SET NULL;
ALTER TABLE prlink ADD CONSTRAINT fk_prlink_cid FOREIGN KEY ("cid") REFERENCES "user" (id) ON DELETE SET NULL;