// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgKind } from "./OrgKind";

export interface Org { id: bigint, name: string | null, kind: OrgKind, cid: bigint, ctime: string, mid: bigint, mtime: string, }