// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgKind } from "./OrgKind";

export interface Org { id: number, name: string | null, kind: OrgKind, cid: number, ctime: string, mid: number, mtime: string, }