// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PackVersion { id: bigint, org_id: bigint, pack_id: bigint, version: string, file_path: string, file_size: bigint, changelog: string | null, cid: bigint, ctime: string, mid: bigint, mtime: string, }