// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Pack { id: number, name: string, org_id: number, cid: number, ctime: string, mid: number, mtime: string, }