// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Pack { id: bigint, name: string, cid: bigint, ctime: string, mid: bigint, mtime: string, }