// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PackVersion { id: number, org_id: number, pack_id: number, version: string, file_path: string, file_size: number, changelog: string | null, cid: number, ctime: string, mid: number, mtime: string, }