// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Prlink { id: number, code: string, user_id: number, cid: number, ctime: string, mid: number, mtime: string, }