// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Prlink { id: bigint, code: string, user_id: bigint, cid: bigint, ctime: string, mid: bigint, mtime: string, }