// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTyp } from "./UserTyp";

export interface User { id: number, username: string, typ: UserTyp, }