// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ORoleName } from "./ORoleName";

export interface UserOrg { id: number, role: ORoleName, org_id: number, user_id: number, cid: number, ctime: string, mid: number, mtime: string, }